/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exercicio.calculadora;

import javax.swing.JSpinner;

/**
 *
 * @author diego
 */
public class calculadoraJava extends javax.swing.JFrame {

    /**
     * Creates new form calculadoraJava
     */
    public calculadoraJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JSpinner();
        btnClick = new javax.swing.JButton();
        lblRDD = new javax.swing.JLabel();
        lblEC = new javax.swing.JLabel();
        lblRQ = new javax.swing.JLabel();
        lblRC = new javax.swing.JLabel();
        lblVA = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        lblEle = new javax.swing.JLabel();
        lblRaizq = new javax.swing.JLabel();
        lblRaizc = new javax.swing.JLabel();
        lblVal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Informe Um Valor:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Calculadora");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnClick.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClick.setText("Calcular");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        lblRDD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblEC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblRQ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblRC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblVA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblRes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblEle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblRaizq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblRaizc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblVal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRDD)
                            .addComponent(lblEC)
                            .addComponent(lblRQ)
                            .addComponent(lblRC)
                            .addComponent(lblVA)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVal)
                                    .addComponent(lblRaizc)
                                    .addComponent(lblRaizq)
                                    .addComponent(lblEle)
                                    .addComponent(lblRes))
                                .addGap(136, 136, 136)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRDD)
                    .addComponent(lblRes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEC)
                    .addComponent(lblEle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRQ)
                    .addComponent(lblRaizq))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRC)
                    .addComponent(lblRaizc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVA)
                    .addComponent(lblVal))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        
         lblRDD.setText("Resto da Divisão por 2:");
        lblEC.setText("Elevado ao Cubo:");
        lblRQ.setText("Raiz Quadrada:");
        lblRC.setText("Raiz Cúbica:");
        lblVA.setText("Valor Absoluto:");
        
        int num = Integer.parseInt(txtValor.getValue().toString());
        
        int res = (int) num % 2;
        float elev = (float) Math.pow(num, 3);
        float raizq = (float) Math.sqrt(num);
        float raizc = (float) Math.cbrt(num);
        int valora = (int) Math.abs(num);
        
        
        lblRes.setText(Integer.toString(res));
        
        lblEle.setText(String.format("%.2f", elev));
        
        lblRaizq.setText(String.format("%.2f", raizq));
        
        lblRaizc.setText(String.format("%.2f", raizc));
        
        lblVal.setText(Integer.toString(valora));
    }//GEN-LAST:event_btnClickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadoraJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadoraJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadoraJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadoraJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadoraJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEC;
    private javax.swing.JLabel lblEle;
    private javax.swing.JLabel lblRC;
    private javax.swing.JLabel lblRDD;
    private javax.swing.JLabel lblRQ;
    private javax.swing.JLabel lblRaizc;
    private javax.swing.JLabel lblRaizq;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblVA;
    private javax.swing.JLabel lblVal;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables

    private String getText(JSpinner txtValor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
